INSERT INTO Books VALUES (1,'Genesis');
INSERT INTO Books VALUES (2,'Êxodo');
INSERT INTO Books VALUES (3,'Levítico');
INSERT INTO Books VALUES (4,'Números');
INSERT INTO Books VALUES (5,'Deuteronômio');
INSERT INTO Books VALUES (6,'Livro de Josué');
INSERT INTO Books VALUES (7,'Livro dos Juízes');
INSERT INTO Books VALUES (8,'Livro de Rute');
INSERT INTO Books VALUES (9,'I Livro de Samuel');
INSERT INTO Books VALUES (10,'II Livro de Samuel');
INSERT INTO Books VALUES (11,'I Livro dos Reis');
INSERT INTO Books VALUES (12,'II Livro dos Reis');
INSERT INTO Books VALUES (13,'I Livro das Crônicas');
INSERT INTO Books VALUES (14,'II Livro das Crônicas');
INSERT INTO Books VALUES (15,'Livro de Esdras');
INSERT INTO Books VALUES (16,'Livro de Neemias');
INSERT INTO Books VALUES (17,'Livro de Tobias');
INSERT INTO Books VALUES (18,'Livro de Judite');
INSERT INTO Books VALUES (19,'Livro de Ester');
INSERT INTO Books VALUES (20,'I Livro dos Macabeus');
INSERT INTO Books VALUES (21,'II Livro dos Macabeus');
INSERT INTO Books VALUES (22,'Livro de Jó');
INSERT INTO Books VALUES (23,'Salmos');
INSERT INTO Books VALUES (24,'Livro dos Provérbios');
INSERT INTO Books VALUES (25,'Livro do Eclesiastes');
INSERT INTO Books VALUES (26,'Cântico dos Cânticos');
INSERT INTO Books VALUES (27,'Livro da Sabedoria');
INSERT INTO Books VALUES (28,'Livro do Eclesiástico');
INSERT INTO Books VALUES (29,'Isaías');
INSERT INTO Books VALUES (30,'Jeremias');
INSERT INTO Books VALUES (31,'Lamentações');
INSERT INTO Books VALUES (32,'Baruc');
INSERT INTO Books VALUES (33,'Ezequiel');
INSERT INTO Books VALUES (34,'Daniel');
INSERT INTO Books VALUES (35,'Oséias');
INSERT INTO Books VALUES (36,'Joel');
INSERT INTO Books VALUES (37,'Amós');
INSERT INTO Books VALUES (38,'Abdias');
INSERT INTO Books VALUES (39,'Jonas');
INSERT INTO Books VALUES (40,'Miquéias');
INSERT INTO Books VALUES (41,'Naum');
INSERT INTO Books VALUES (42,'Habacuc');
INSERT INTO Books VALUES (43,'Sofonias');
INSERT INTO Books VALUES (44,'Ageu');
INSERT INTO Books VALUES (45,'Zacarias');
INSERT INTO Books VALUES (46,'Malaquias');
INSERT INTO Books VALUES (47,'Evangelho segundo São Mateus');
INSERT INTO Books VALUES (48,'Evangelho segundo São Marcos');
INSERT INTO Books VALUES (49,'Evangelho segundo São Lucas');
INSERT INTO Books VALUES (50,'Evangelho segundo São João');
INSERT INTO Books VALUES (51,'Atos dos Apóstolos');
INSERT INTO Books VALUES (52,'Epístola de São Paulo aos Romanos');
INSERT INTO Books VALUES (53,'Primeira Epístola aos Coríntios');
INSERT INTO Books VALUES (54,'Segunda Epístola aos Coríntios');
INSERT INTO Books VALUES (55,'Epístola aos Gálatas');
INSERT INTO Books VALUES (56,'Epístola aos Efésios');
INSERT INTO Books VALUES (57,'Epístola aos Filipenses');
INSERT INTO Books VALUES (58,'Epístola aos Colossenses');
INSERT INTO Books VALUES (59,'Primeira Epístola aos Tessalonicenses');
INSERT INTO Books VALUES (60,'Segunda Epístola aos Tessalonicenses');
INSERT INTO Books VALUES (61,'Primeira Epístola a Timóteo');
INSERT INTO Books VALUES (62,'Segunda Epístola a Timóteo');
INSERT INTO Books VALUES (63,'Epístola a Tito');
INSERT INTO Books VALUES (64,'Epístola a Filêmon');
INSERT INTO Books VALUES (65,'Epístola aos Hebreus');
INSERT INTO Books VALUES (66,'Epístola de São Tiago');
INSERT INTO Books VALUES (67,'Primeira Epístola de São Pedro');
INSERT INTO Books VALUES (68,'Segunda Epístola de São Pedro');
INSERT INTO Books VALUES (69,'Primeira Epístola de São João');
INSERT INTO Books VALUES (70,'Segunda Epístola de São João');
INSERT INTO Books VALUES (71,'Terceira Epístola de São João');
INSERT INTO Books VALUES (72,'Epístola de São Judas');
INSERT INTO Books VALUES (73,'Apocalipse');
